// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This was written by Martin Krucinski on 28-Feb-2017 at 21:53
#define Hmin      74.1209
#define Hmax      91.1486
#define Smin      86.3750
#define Smax     199.3347
#define Lmin      82.8039
#define Lmax     110.0000
#define MinHeight      26.0000
#define MinWidth       9.0000
