// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Martin Krucinski on 03-Mar-2017 at 22:11
#define Hmin      59.4118
#define Hmax      76.9549
#define Smin     250.0000
#define Smax     255.0000
#define Lmin      27.1176
#define Lmax      67.6471
#define MinHeight      33.0000
#define MinWidth       8.0000
