// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This was written by Jacob Krucinski on 21-Feb-2017 at 18:21
#define Hmin      76.1224
#define Hmax      92.5000
#define Smin     218.7755
#define Smax     255.0000
#define Lmin      29.8627
#define Lmax     110.0000
#define MinHeight      46.0000
#define MinWidth      12.0000
