// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Martin Krucinski on 05-Mar-2017 at 14:01
#define Hmin      59.8387
#define Hmax      83.1579
#define Smin     179.6552
#define Smax     255.0000
#define Lmin       3.1961
#define Lmax      30.3922
#define MinHeight      24.0000
#define MinWidth       8.0000
