// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Martin Krucinski on 05-Mar-2017 at 14:23
#define Hmin      67.3214
#define Hmax      81.8293
#define Smin     237.7600
#define Smax     255.0000
#define Lmin      35.3529
#define Lmax      66.4706
#define MinHeight      26.0000
#define MinWidth       7.0000
